name = "DifferentiableStateSpaceModels"
uuid = "beacd9db-9e5e-4956-9b09-459a4b2028df"
authors = ["Jesse Perla <jesseperla@gmail.com> and contributors"]
version = "0.1.1"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
TuringCallbacks = "ea0860ee-d0ef-45ef-82e6-cc37d6be2f9c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
julia = "1.5, 1.6"
ChainRulesCore = "0.9.23"
ModelingToolkit = "4.5"
TensorCast = "0.3"
Turing = "0.15, 0.16"
Zygote = "0.6"
BenchmarkTools = "1.0"
CSV = "0.8"
CUDA = "2, 3.3"
DataFrames = "1.1"
Distributions = "0.24"
DistributionsAD = "0.6"
DocStringExtensions = "0.8"
FileIO = "1.9"
FiniteDiff = "2.8"
ForwardDiff = "0.10"
GeneralizedGenerated = "0.3"
KernelAbstractions = "0.6"
LaTeXStrings = "1.2"
Latexify = "0.14"
LoopVectorization = "0.10"
MacroTools = "0.5"
MatrixEquations = "1.3"
NLsolve = "4.5"
Optim = "1.3"
Parameters = "0.12"
PkgBenchmark = "0.2"
RecursiveArrayTools = "2.11"
Revise = "3"
SpecialFunctions = "1.5"
StaticArrays = "1.2"
StatsPlots = "0.14"
TensorBoardLogger = "0.1"
TensorOperations = "3.2"
TimerOutputs = "0.5"
Tullio = "0.2"
TuringCallbacks = "0.1"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Plots"]
