name = "DifferentiableStateSpaceModels"
uuid = "beacd9db-9e5e-4956-9b09-459a4b2028df"
authors = ["Jesse Perla <jesseperla@gmail.com> and contributors"]
version = "0.1.1"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DistributionsAD = "ced4e74d-a319-5a8a-b0ac-84af2272839c"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
TensorCast = "02d47bb6-7ce6-556a-be16-bb1710789e2b"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
TuringCallbacks = "ea0860ee-d0ef-45ef-82e6-cc37d6be2f9c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Distributions = "0.24"
DistributionsAD = "0.6"
ModelingToolkit = "4.5"
NLsolve = "4.5"
Parameters = "0.12"
TensorCast = "0.3"
Zygote = "0.5"
julia = "1.6"
ChainRulesCore = "0.5, 0.6, 0.7, 0.9, 0.10"
DocStringExtensions = "0.8"
GeneralizedGenerated = "0.3"
LaTeXStrings = "1.2"
MacroTools = "0.5"
MatrixEquations = "1.5"
StatsPlots = "0.14"
TimerOutputs = "0.5"
TuringCallbacks = "0.1"